insert into funcionarios (codigo, nome, salario, celular)
values (1, 'Amanda', 2600, '11987465471');
insert into funcionarios (codigo, nome, salario, celular)
values (2, 'Alonso', 1800, '11987521458');
insert into funcionarios (codigo, nome, salario, celular)
values (3, 'Alisson', 3500, '11961465845');
insert into funcionarios (codigo, nome, salario, celular)
values (4, 'Aurelio', 2900, '11985214751');
insert into funcionarios (codigo, nome, salario, celular)
values (5, 'Bruno', 3200, '11963258741');
insert into funcionarios (codigo, nome, salario, celular)
values (6, 'Bernardo', 3500, '11987456321');
insert into funcionarios (codigo, nome, salario, celular)
values (7, 'Carlos', 2600, '11963258258');
insert into funcionarios (codigo, nome, salario, celular)
values (8, 'Paulo', 1450, '11963698523');
insert into funcionarios (codigo, nome, salario, celular)
values (9, 'Joice', 8000, '11965478485');
insert into funcionarios (codigo, nome, salario, celular)
values (10, 'Jeremias', 7500, '11963254124');

insert into funcionarios values (11, 'Jonatan', 5000, '11925478451');
insert into funcionarios values (12, 'Gabriel', 2600, '11954784851');
insert into funcionarios values (13, 'Giane', 3000, '11996365854');
insert into funcionarios values (14, 'Ronaldo', 1800, '11909658720');
insert into funcionarios values (15, 'Marta', 3200, '11903214578');
insert into funcionarios values (16, 'Wesley', 5600, '11905487874');
insert into funcionarios values (17, 'Everton', 8900, '11903245781');
insert into funcionarios values (18, 'Marcio', 6200, '11996354808');
insert into funcionarios values (19, 'Valmir', 7500, '11932054870');
insert into funcionarios values (20, 'Tereza', 11000, '11913468045');